### ISSUE TITLE
How to use with scroll view

### ISSUE THREAD

**Issue by desh2608** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#10]
I have a CompanyList class which contains an accordion inside a scroll view. I want to implement PullToRefresh on this scroll view. I have added the scroll view as a child of the refreshView.

I am not sure how to use the SetBinding statements. Can someone help with that? Currently when I pull down, all that happens is that the loading animation appears and stays forever.

**Comment by jamesmontemagno** [comment]
Take a look at my samples: https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/blob/master/RefreshSample/Views/ScrollViewXamlPage.xaml
