### ISSUE TITLE
Help adding UWP support

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#11]
I have been trying to add UWP support to this plugin but I am getting nowhere. UWP doesn't have a native control for it and the only decent example of it being done on UWP I can find is a sample from Microsoft (https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlPullToRefresh), but for the life for me I can't figure out how to use that logic to add it to the plugin. UWP support would be awesome, since even Xamarin's listview doesn't have support for pull to refresh on UWP.

@jamesmontemagno do you have any plans to add UWP support, or advice on how it could be done? Any help would be greatly appreciated

**Comment by jamesmontemagno** [comment]
No plans to add UWP at this point as it is a custom listview control. Would be a good PR to send to the Xamarin.Forms repo directly.
