### ISSUE TITLE
PulltoRefresh + await FadeTo+TranslateTo animation combination Crash.

### ISSUE THREAD

**Issue by allbdeveloper** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#14]
I'm having really hard time to solve this issue. I've spent several days but couldn't solve.

I'm using this nuget
- PullToRefresh 
  https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout
- xabre ble plugin 
  https://github.com/xabre/xamarin-bluetooth-le

When I use this at the same time AND Add some animation on the page. It gives this runtime exception when I try to refresh. (It happens very rare like 1 time on 10 times)
- The Crash happens ONLY iOS.
- It's very rare. You can try to refresh more than 10 times. You will see.
- It happens only actual iOS Device.

> Foundation.MonoTouchException: Objective-C exception thrown. Name: NSGenericException Reason: **\* Collection <__NSSetM: 0x14feb8b0> was mutated while being enumerated.

I know well what this is and when this happen. It happens when I try to access deleted item on list or different thread.

So I made very simple source code to look this issue simply. I don't have any list or array on my code. Well, it happens again.

**Reproduce Sample Code**
https://github.com/myallb/test_pulltorefresh

This is my sample source code for reproducing this issue. If you can help me, please look this code.

**Comment by allbdeveloper** [comment]
I tried to remove all ble modules, and still got crash.

**Comment by jamesmontemagno** [comment]
Make sure you do stuff on the UI Thread maybe? I don't see the repo anymore. CLosing
