### ISSUE TITLE
The Android version of pull to refresh layout is confusing. 

### ISSUE THREAD

**Issue by Emasoft** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#15]
This is a very important functionality for the listview component. It should be included in  Xamarin.Forms. But the Android version of pull to refresh layout is confusing. An animated icon appears from above, but the list is not pulled down. My clients are confused by it. Are you going to improve it in the future?

**Comment by jamesmontemagno** [comment]
1.) Xamarin.Forms already includes pull to refresh in the ListView. this extends to the ScrollView
2.) That is the standard layout for Android, there is nothing confusing about it.
