### ISSUE TITLE
PullToRefresh doesn't trigger on IOS.

### ISSUE THREAD

**Issue by Arohdin** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#18]
I've implemented PullToRefresh (called ptr) in my PCL project and it's currently working on android, but not ios.

I've created the ptr as done in the given exampels and I've also explicitly set IsPullToRefreshEnabled = true just to be sure it doesn't initiate with different values depending on platform.
The content property of my ptr-object got a ScrollView bound to it and I've also bound the viewmodel 'IsBusy' property and 'Loading'-command.

When pulling the scrollview in the ios version nothing happens.

This was tested on iOS emulator with iOS version 10 running on it.

**Comment by jamesmontemagno** [comment]
I will need a sample and more info. Not having any issues here.
