### ISSUE TITLE
Every move down this activating the pull

### ISSUE THREAD

**Issue by elyfran** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#2]
Hi,

Every move down this activating the pull . this is normal?

would have set a radio to activate the pull so well ?

**Comment by jamesmontemagno** [comment]
I am not sure what you mean by this.

**Comment by elyfran** [comment]
First thanks for answering.
Every movement in any position in the list is being activated. Would only be activated at the beginning of the list. You Agree?

The problem is happening because this being activated at the beginning, middle and end, anywhere you make the move down is activated.

Understood?

**Comment by elyfran** [comment]
below is an example of code:

StackLayout layout = new StackLayout { Padding = 5 };

ListView listView = new ListView()
                    {
                        HasUnevenRows = true,
                        SeparatorVisibility = SeparatorVisibility.Default,
                        ItemsSource = clientER.ListaDeAnuncios,
                        BackgroundColor = Color.White,
                        SeparatorColor = Color.Transparent,
                        IsPullToRefreshEnabled=true,
                        ItemTemplate = new DataTemplate(typeof(CaseCell))
                    };

                layout.Children.Add(listView);

var scrollView = new ScrollView
                {
                    Padding = 0,
                    VerticalOptions = LayoutOptions.FillAndExpand,
                    HorizontalOptions = LayoutOptions.FillAndExpand,
                    Content = layout
                };

            var refreshView = new PullToRefreshLayout {
                Padding = 0,
                VerticalOptions = LayoutOptions.FillAndExpand,
                HorizontalOptions = LayoutOptions.FillAndExpand,
                Content = scrollView,
                IsPullToRefreshEnabled=true,
                RefreshColor = Color.Black,
                RefreshBackgroundColor = Color.White
            };

            refreshView.SetBinding<ParceiroER> (PullToRefreshLayout.IsRefreshingProperty, vm => vm.IsBusy, BindingMode.OneWay);
            refreshView.SetBinding<ParceiroER>(PullToRefreshLayout.RefreshCommandProperty, vm => vm.RefreshCommand);

            Content = new StackLayout
                {
                    Padding = 0,
                    Children = 
                        {
                            refreshView
                        }
                    };

**Comment by jamesmontemagno** [comment]
You can't put a ListView inside of a ScrollView as bad things would happen there unless you calculate the height of the ListView manually. 

In this case you are using just a ListView, which has pull to refresh built in: http://motzcod.es/post/113280718807/official-pull-to-refresh-in-xamarinforms-140


You can only use the RefreshLayout with a ScrollView or a ListView as the child
