### ISSUE TITLE
Custom gif instead of default loader 

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#21]
Hi,
This is really awesome plugin.

But I have a situation where I need to use my own gif when refreshing scroll view. 
So how to disable the default loader and show mine?
Of course it should still refresh the page !

**Comment by jamesmontemagno** [comment]
Not sure I can help you as that doesn't pertain to the plugin really. You would need to fork the code and then probably implement the part where it looks for specific controls to work with.

**Comment by avinashramireddy-rapidd** [comment]
It's OK. I will try myself. 

Just for clarity,is it possible to hide loader when pulling down but refresh in behind the scenes.
I can show my gif when refreshing but need to hide white circle.
I tried setting color matching with my background color.But in between I have my gif image which have different color.

If not I will fork and try myself.
