### ISSUE TITLE
Need to pull further than the screen height on iOS

### ISSUE THREAD

**Issue by hardcodet** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#24]
I'm seeing a weird issue on iOS here: When pulling down my custom control, the refresh indicator starts to fill, but once my finger is at the end of the screen, I'm only at 75%. I literally have to use both hands to drag the control down enough in order to trigger the refresh. Works fine on Android though.

<img src="https://cloud.githubusercontent.com/assets/873009/25938310/0fa84834-362f-11e7-9d09-3490a8abd953.png" width="300"></img>

**Comment by jamesmontemagno** [comment]
What is your hierarchy like?

**Comment by hardcodet** [comment]
I just checked: This seems to have been related to an issue with the CarouselControl that is going to make its entry into Xamarin: This somehow messes up height calculation with StackLayouts in the mix:
https://github.com/alexrainman/CarouselView/issues/123

I changed the UI composition recently to work around the issue and just noticed that the layout issue with the PullToRefreshLayout (which was used on a carousel sheet) is gone, too. Closing this now.

**Comment by jamesmontemagno** [comment]
:)
