### ISSUE TITLE
ActivityIndicator not showed (IsRefreshing changed programmatically)

### ISSUE THREAD

**Issue by xportation** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#27]
If I change the IsRefreshing property programmatically the ActivityIndicator is not showed.   
It's differs the ListView...  
  
![pulltorefreshlayout](https://user-images.githubusercontent.com/4412615/29756054-c45028b4-8b76-11e7-8d54-a19ab450f8dd.gif)
  
  
Do you know how to have same behavior??  

Thanks :)

**Comment by couper321** [comment]
I also receive similar behavior only on iOS, my Android platform works fine.

**Comment by AlejoZito** [comment]
Same problema here. It looks like the container that holds the spinner doesn´t expand when IsRefreshing is set to true from the viewmodel. Issue only happens on iOS

**Comment by batkuip82** [comment]
Had the same issue... Not sure if its a binding issue, because I seemed to work around the issue by setting the IsRefresh property directly on the control (e.g. in code-behind). Not a very elegant solution though :)

**Comment by scriptBoris** [comment]
Problem is actual
