### ISSUE TITLE
Can't refresh automatically upon page load.

### ISSUE THREAD

**Issue by BillyMartin1964** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#28]
I love your pull to refresh. I’m using it in scrollviews, but I can’t get it to BeginRefresh automatically when the page loads. I’ve tried hooking it to the controls and to the scrollview, but both say there is no BeginRefresh. Do you have a way to load the data from  ICommand on page load in Xamarin Forms PCL?

Thanks!

**Comment by c-lamont** [comment]
Having the same issue with activating the refresh spinner when the page loads while attached to a ScrollView.

I also have an issue in iOS while attached to a ListView. I had to set my bound refresh property to true inside the constructor, but then the color is black and not my specified color.

**Comment by jamesmontemagno** [comment]
Duplicate of https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/issues/27
