### ISSUE TITLE
Not working for IOS

### ISSUE THREAD

**Issue by band888888** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#33]
PCL project.

1).i register this (PullToRefreshLayoutRenderer.Init();)  in AppDelegate.cs.

2).I create a xaml page and use the 

<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    x:Class="RefreshSample.Views.ScrollViewXamlPage"
    xmlns:controls="clr-namespace:Refractored.XamForms.PullToRefresh;assembly=Refractored.XamForms.PullToRefresh"
    Title="Xaml Scroll">
   <controls:PullToRefreshLayout
          IsPullToRefreshEnabled="True"
          RefreshCommand="{Binding RefreshCommand}"
          IsRefreshing="{Binding IsBusy}"
          RefreshColor="Blue"> 

My listvew

 </controls:PullToRefreshLayout>
</ContentPage>

Then the page is a blank page. 

Any idea?

**Comment by jamesmontemagno** [comment]
Did you try the sample in here? works good for me
