### ISSUE TITLE
ExecuteRefreshCommand runs synchronously?

### ISSUE THREAD

**Issue by PaulGH** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#38]
Hi,
just running thru the code and noticed that the intellisense is indicating that the ExecuteRefreshCommand runs synchronously because its missing an await. "This async method lacks await operators..." 
Is this a legit issue? 
Thanks

**Comment by Miiite** [comment]
It's probably just that james used some kind of await Task.Delay at some point of the project. But being in the TestViewModel class, it's not an issue linked to the library, just a syntax thing of the sample project. Not really relevant here.

**Comment by jamesmontemagno** [comment]
Please use the RefreshView as this is officially deprecated now https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview
