### ISSUE TITLE
Crashing on DetailView change

### ISSUE THREAD

**Issue by victorarce** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#4]
Hi James, 

I'm having a weird issue and no detailed information comes up, just a null reference error.
This is how I reproduce it:
1) I have a master-detail page view (actually based on your CRM project =) )
2) Lets say I have 2 detail pages. When I load the page with the PullToRefreshLayout view, it works fine until... I select another page on the side-drawer menu, right after setting  Detail = displayPage in the NavigateTo(option) method, this in the root class.
 I followed execution step-by-step and the last code it executes is in the OnElementPropertyChanged event and Dispose deconstructor then it suddenly crashes. This is of course, in the renderer class.

Push and Modal Push work fine on top the PullToRefreshLayout view, the problem relies only when changing the Detail page and same behavior in both Droid/iOS. 

I debugged for null objects but couldn't find anything odd in my code. There has to be some kind of override that needs to be implemented in the renderer class for the control to be dispossed. (Im just assuming)

Any help will be great

best regards

**Comment by jamesmontemagno** [comment]
I believe this was fixed in most recent version.
