### ISSUE TITLE
Pull to refresh crash after upgrading to new Xamarin, new Android support

### ISSUE THREAD

**Issue by DrorSegev** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#41]
No clue where to start looking:

Exception:
 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#
 	0x33 in object.58389086-8607-4cf9-a735-5092a7d30364	C#
 	0x5 in R**efractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer.get_View**	C#
 	0x53 in Xamarin.Forms.Platform.Android.VisualElementTracker..ctor at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:36,4	C#
 	0x59 in Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer.SetElement	C#
 	0x26 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314,4	C#
 	0x55 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:97,5	C#
 	0x116 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:231,6	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:76,4	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetPackager at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:385,4	C#
 	0xD6 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.SetElement at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:179,5	C#
 	0x2E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.View>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125,4	C#
 	0x26 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:314,4	C#
 	0x55 in Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:97,5	C#
 	0x116 in Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:231,6	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementPackager.Load at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:76,4	C#
 	0x8 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.Page>.SetPackager at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:385,4	C#
 	0xD6 in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.Page>.SetElement at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:179,5	C#
 	0x2E in Xamarin.Forms.Platform.Android.VisualElementRenderer<Xamarin.Forms.Page>.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:125,4	C#
 	0x38 in Xamarin.Forms.Platform.Android.Platform.CreateRenderer at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Platform.cs:361,4	C#
 	0x1B in Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnCreateView at D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:67,5	C#
 	0x24 in Android.Support.V4.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_	C#

Dror

**Comment by jamesmontemagno** [comment]
Please use the RefreshView as this is officially deprecated now https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview
