### ISSUE TITLE
Purpose of IsPullToRefreshEnabledProperty?

### ISSUE THREAD

**Issue by JunkyXL86** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#42]
Setting IsPullToRefreshEnabledProperty to false seems to not affect anything. You can still pull the refresher down. I was expecting to happen nothing when you try to pull down.
Also the refresher appears even when there is no RefreshCommand set. That makes imo no sense, as it does nothing but showing an animating icon.

**Comment by kchan4** [comment]
I have the same problem even setting IsPullToRefreshEnabledProperty it still allow for refreshing :(

**Comment by Welchen** [comment]
Running into the same problem myself.

**Comment by nielscup** [comment]
I had the same problem when setting IsPullToRefreshEnabled to false in code. The first time it was disabled but reloading the same page it got enabled again magically, even when explicitely setting it to false. I eventually solved it by binding the IsPullToRefreshEnabled property, kind of weird but then it works correctly.

**Comment by jamesmontemagno** [comment]
Please use the RefreshView as this is officially deprecated now https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview
