### ISSUE TITLE
Extra space in ios

### ISSUE THREAD

**Issue by bastianbecker21** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#45]
I implemented pull-to-refresh using this package and worked good.
But I am facing only one problem in ios.
Sometimes after it refresh, the space that activity indicator was placing is not removed in ios.
Please help me to fix it.
Thanks.

**Comment by leonvandebroek** [comment]
i am experiencing the same problem. It started about two months ago. Don't know exactly when. Could it be related to iOS 11.3? the problems started right around the time the first beta's were released.

**Comment by irreal** [comment]
Can confirm I had this implemented for a long while, made no changes to my code or any nuget package versions, yet it started to leave the empty space where the indicator was.

**Comment by msjjd** [comment]
same problem

**Comment by jamesmontemagno** [comment]
Can you give me sample xaml? Can your repo in the sample in this repo?

**Comment by bastianbecker21** [comment]
@jamesmontemagno I've got the exact case that it works wrong.
I have a ContentView in page and I replace 3 different ContentViews to show different layouts in that ContentView.

Here is the ContentView in page
```
<ContentView
      HorizontalOptions="FillAndExpand"
      VerticalOptions="FillAndExpand"
      x:Name="ContentPresenter"/>
```
 First One in 3 ContentViews has pull-to-refresh layout.
<ContentView.Content>
        <controls:PullToRefreshLayout
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand"
            IsPullToRefreshEnabled="True"
            RefreshCommand="{Binding RefreshHomeProfileCommand}"
            IsRefreshing="{Binding IsLoadingDialogVisible}">
            <ScrollView
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand"
                Padding="15,15,15,15">
                <StackLayout
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand"
                    Spacing="15">
                    ....
                    ...
                </StackLayout>
            </ScrollView>
        </controls:PullToRefreshLayout>
</ContentView.Content>

This first layout is default view to show to user in parent ContentView.
When app opens, pull-to-refresh works good and it doesn't have extra space after pull.
But It always have extra space whenever changing ContentViews by clicking button after show other 2 ContentViews.

Please let me know if any misunderstanding.
Thanks and Hope to help to fix issue!

**Comment by bastianbecker21** [comment]
@jamesmontemagno any update here?

**Comment by MrHyde-** [comment]
Updated our project nuget packages and empty space is now appearing on every refresh. Reverted the package back to the version 2.0.0.13 and everything seems working again. 

Then decided to test the 2.2.0 package and the white space isn't appearing either..

Our application supports Android and iOS and the problem is occurring only in the iOS.

**Comment by bastianbecker21** [comment]
I am trying to downgrade the package to 2.0.0.13 but no luck, it's not downgraded and shows error.
It's Visual Studio Mac error or package error?
Please help me to fix, thanks.

**Comment by tkohub** [comment]
Same issue here. Can't fix it with any version back to 2.0.0.13

@MrHyde- You managed to get it working with an older version?

**Comment by bastianbecker21** [comment]
I wasn't able to even revert it to 2.0.0.13. not sure why...

**Comment by tkohub** [comment]
@jamesmontemagno Can we expect any update on this in the near future? We would be really happy about a fix since we are constantly using the framework and we really like it.

**Comment by MrHyde-** [comment]
@tkohub yes, we have the problem with our project only with the newest package. But the 2.2.0 version works fine for us.

**Comment by bastianbecker21** [comment]
@MrHyde- do you have release log for this package? I want to know what is difference between 2.2.0 and 2.2.1. You released 2.2.1 very soon after 2.2.0, is there any critical issue in 2.2.0? I am afraid to face another problem with 2.2.0

**Comment by jamesmontemagno** [comment]
does anyone have a screen shot and a small sample?

**Comment by jamesmontemagno** [comment]
Can you please validate: 2.2.1.27-beta and let me know if you see any issues there.

**Comment by MrHyde-** [comment]
For our project the problem does not appear in the  beta version. Tested with simulator and real device. Thank you!

**Comment by jamesmontemagno** [comment]
If anyone else can validated I will push 2.2.2 out tonight or tomorrow

**Comment by tkohub** [comment]
Sorry for coming back to you so late, i was on holiday till today.

For me it is working as well! Thanks a lot
