### ISSUE TITLE
Does not stop showing 'refreshing' indicator on iOS after refresh complete

### ISSUE THREAD

**Issue by amcculloch-fd** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#5]
Working perfect in Android but not in iOS.

After I set:-

IsBusy = false;
RefreshCommand.ChangeCanExecute ();

Refreshing indicator does not disappear. You cannot pull to refresh again.

IsBusy property is being called after setting IsBusy = false so looks like binding is working.

**Comment by amcculloch-fd** [comment]
Resolved with some updates - not sure exactly what was causing the issue

**Comment by allbdeveloper** [comment]
In my case. 

			Device.BeginInvokeOnMainThread(() =>
				{
					refreshView.IsRefreshing = false;
				});
works.

**Comment by pamela032709** [comment]
so what is the fix ?
