### ISSUE TITLE
System.InvalidOperationException: Page must not already have a parent.

### ISSUE THREAD

**Issue by ghost** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#50]
I am trying to run this project, after clicking on the button this exception happening.

**Comment by jamesmontemagno** [comment]
which button?

**Comment by jamesmontemagno** [comment]
Would need a repro project.

**Comment by jamesmontemagno** [comment]
Please use the RefreshView as this is officially deprecated now https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview
