### ISSUE TITLE
PullToRefreshLayout cut off the page top

### ISSUE THREAD

**Issue by viniciusmaia** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#51]
I'm using PullToRefreshLayout with a ScrollView and, in iOS platform, when my page load and the IsRefreshing property is set to false, the top of the page is cut off.

**Comment by Serwerty** [comment]
Have the same issue.

**Comment by mnikonov** [comment]
same issue

**Comment by michelzsiqueira** [comment]
UP

**Comment by khoduley** [comment]
the same

**Comment by jamesmontemagno** [comment]
Screenshots... info... repro... anything?
