### ISSUE TITLE
Cannot scroll back up when scrollview has scrolled down on Android

### ISSUE THREAD

**Issue by MohammedSadiq123** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#53]
When you swipe up to make the scrollview go down, once the scrollview is at the bottom of the page, if you swipe down to go up it will always trigger the PullToRefresh feature. You won't be able scroll up anymore and the scrollview will get stuck.

sample:

`<ContentPage.Content>

    <pull:PullToRefreshLayout

        IsPullToRefreshEnabled="True"

        RefreshCommand="{Binding RefreshCommand}"

        IsRefreshing="{Binding IsRefreshing}"

        RefreshColor="Black">

        <Grid

            HeightRequest="{DynamicResource ScreenHeight}">

            <controls:CustomNavigavtionBarControl

                OpenSearchBoxCommand="{Binding OpenSearchBoxCommand, Mode=TwoWay }"

                OpenNotificationCommand="{Binding OpenNotficationPageCommand }"

                BackCommand="{Binding BackCommand}" />

            <ScrollView

                Margin="{DynamicResource RootContentThickness}">

                <StackLayout

                    Spacing="0"

                    Padding="{StaticResource RightLeftThicknessX}"

                    Orientation="Vertical">

                    <StackLayout`

**Comment by jamesmontemagno** [comment]
Grid is not officially supported as the root object, only ScrollView/ListView

**Comment by Nanouz** [comment]
How can you fix this problem?

**Comment by nelsonnil** [comment]
I would be very grateful if someone could help us solve this problem
