### ISSUE TITLE
 After upgrade Xamarin Forms 3.3.0 gave a bug

### ISSUE THREAD

**Issue by michelzsiqueira** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#55]
After upgrading xamarin forms to version 3.3.0 the PullToRefreshLayout package stopped working.

**Comment by michelzsiqueira** [comment]
sorted out

**Comment by sqrg** [comment]
> sorted out

May I ask what was the problem? Because I'm experiencing something similar and cannot upgrade to the latest version

**Comment by michelzsiqueira** [comment]
I do not remember how I solved it, I do not use this library anymore.
