### ISSUE TITLE
Forms 3.4 causes crash when init the plugin

### ISSUE THREAD

**Issue by raymondjstone** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#57]
PullToRefreshLayoutRenderer.Init(); fails (android in this case)

Unhandled Exception:

System.TypeLoadException: VTable setup of type Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer failed

**Comment by nielscup** [comment]
same issue here, only on Android. iOS works fine

**Comment by quentinR0bert** [comment]
see #56

**Comment by jamesmontemagno** [comment]
Duplicate of #56
