### ISSUE TITLE
What is release note for new version 2.2.3 of package in nuget?

### ISSUE THREAD

**Issue by bastianbecker21** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#58]
Hi, I can't find release note for new version of 2.2.3 of package in nuget. Please provide me so that I can know what is fixed, Thanks

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/blob/master/CHANGELOG.md
