### ISSUE TITLE
TypeLoad Exception on Init in Android 

### ISSUE THREAD

**Issue by davidmaiden** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#60]
Following update of Xamarin.Forms to 3.6.220655 I get a System.TypeLoadException on Android in MainActivity when calling PullToRefreshLayoutRenderer.Init()

Works ok with Xamarin.Forms 3.5.0.169047

**Comment by jamesmontemagno** [comment]
Duplicate #62, try new pre-release
