### ISSUE TITLE
PullToRefresh intercepts Horizontal Swipe of carouselView inside it

### ISSUE THREAD

**Issue by jerryno6** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#69]
I use Horizontal CarouselView inside PullToRefreshLayout.
on Android, while User's swiping horizontal, If the user bear down a little bit, the PullToRefresh behavior will intercept the horizontal swipe. There is a solution to fix it in the thread below, but it is not implemented in this source code. Should we add it & export an option for this control such as: InterceptHorizontalScroll = false/true.

[https://github.com/jerryno6/Xamarin.Forms-PullToRefreshLayout.git](https://github.com/jerryno6/Xamarin.Forms-PullToRefreshLayout.git)

If there is no problem with it, I will Fork this, edit the codes and make a pull request to you.

**Comment by jamesmontemagno** [comment]
Can you send a PR to add this property.

**Comment by jerryno6** [comment]
I have created a pull request as below
[https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/pull/70](https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/pull/70)
