### ISSUE TITLE
IsRefreshing=False not Working.

### ISSUE THREAD

**Issue by Sivamuralidhar** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#7]
Hi James ,

this control is really cool.thanks for posting it.

While using pull to refresh am getting an issue,
after refreshing am trying to set IsRefreshing= false but unfortunately this option is not working and the spinner is displaying always.

Thanks,
Sivamuralidhar.

**Comment by dcasbonne** [comment]
HI @Sivamuralidhar . No problem here, in my command I can set IsRefreshing=false and it disables the spinner.
Can you provide a sample of your code ?

**Comment by jamesmontemagno** [comment]
Can't reproduce here.

**Comment by abozanona** [comment]
Hello sir,
I'm facing this problem too, here's a sample of me code

```
<controls:PullToRefreshLayout
          x:Name="ptrLatestNews"
          IsPullToRefreshEnabled="True"
          IsRefreshing="False"
          RefreshColor="Blue">
```

```
var command = new Command(async () => await getConnection());
            ptrLatestNews.RefreshCommand = command;
```

```
private async Task getConnection()
{
    ....
    Device.BeginInvokeOnMainThread(() =>
    {ptrLatestNews.IsRefreshing = false;
    });
    ....
}
```
