### ISSUE TITLE
System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by 1iveowl** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#71]
I get this error when trying to use PullToRefreshLayout with Xamarin Forms 4.1.0.555618 w/ iOS:

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xamarin.Forms.Xaml.XamlParseException: Position 296:14. Default constructor not found for type Refractored.XamForms.PullToRefresh.PullToRefreshLayout ---> System.MissingMethodException: Default constructor not found for type Refractored.XamForms.PullToRefresh.PullToRefreshLayout

**Comment by 1iveowl** [comment]
I think it is linking related. As I added `--linkskip=Refractored.XamForms.PullToRefresh` to the "Additional mtouch arguments the issue went away. 

I'm using "Link All" as Linker Behavior to minimize App size.

**Comment by jamesmontemagno** [comment]
Yeah, you will probably need to link skip :) Glad you got it all fixed up.
