### ISSUE TITLE
Applied On CollectionView , it does not show results after refresh

### ISSUE THREAD

**Issue by Elashi** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#72]
The first time I open my page , it fills data correctly. But after I pull to refresh, I see blank page.  I have to visit another page and get back to it to see the results.
I have put it around a CollectionView and I only tested it on Android emulator.

**Comment by jamesmontemagno** [comment]
I believe this is most likely a bug with CollectionView based on how you are using ObservableCollection to clear and add. I do this: https://github.com/jamesmontemagno/Hanselman.Forms/blob/vnext/src/Hanselman/Views/Blog/BlogCollectionPage.xaml.cs#L33-L39

**Comment by Elashi** [comment]
Your code is perfect.  It was my mistake.  My code that fills the ObservableCollection filled inconsistent results causing the view to show inconsistent results.
Thank you
