### ISSUE TITLE
RefreshCommand not called

### ISSUE THREAD

**Issue by pongo1996** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#77]
**XAML**
 <ContentPage.Content>
        <controls:PullToRefreshLayout
          IsPullToRefreshEnabled="True"
          RefreshCommand="{Binding RefreshCommand}"
          IsRefreshing="{Binding IsBusy, Mode=OneWay}"
          RefreshColor="Red">
            <Grid x:Name="controlGrid" RowSpacing="0" ColumnSpacing="0">
            <Grid.RowDefinitions>...

**CS**
 bool _isBusy;
        public bool IsBusy
        {
            get { return _isBusy; }
            set
            {
                _isBusy = value;
                OnPropertyChanged(nameof(IsBusy));
            }
        }

        private async void PopulateList()
        {
            await DisplayAlert("asd", "asd", "adf");
            IsBusy = true;
            a = 67;
            IsBusy = false;
        }

        public Command RefreshCommand
        {
            get
            {
                return new Command(() =>
                {
                    PopulateList();
                });
            }
        }

I call  **PullToRefreshLayoutRenderer.Init();** in Project.Android in OnCreate.

**Comment by jamesmontemagno** [comment]
Please use the RefreshView as this is officially deprecated now https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview
