### ISSUE TITLE
Getting double spinner on iOS only

### ISSUE THREAD

**Issue by marceloarchiza** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#78]
I am getting double spinner on iOS only. Any ideas why?

![double spinner](https://user-images.githubusercontent.com/38107971/74276389-dc3c3d80-4cd2-11ea-85d7-095b2e55c0c4.png)

Here is the XAML code. I believe is because I have a ScrollView and iOS scrollview already has the pullToRefresh functionality. Any thoughts?
`<ContentPage.Content>
        <Grid x:DataType="..." >
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>

            <customViewControl
                Grid.Row="0"
                HeightRequest="56" />

            <pullToRefresh:PullToRefreshLayout
                IsPullToRefreshEnabled="True"
                RefreshCommand="{Binding RefreshCommand}"
                IsRefreshing="{Binding IsRefreshing, Mode=TwoWay}"
                Grid.Row="1">
                <ScrollView
                    x:Name="ItemsScrollView">
                    <controls:ExtendedStackLayout
                        IsRefreshing="{Binding IsRefreshing}"
                        ItemsSource="{Binding Items}">
                        <controls:ExtendedStackLayout.ItemTemplate>
                            <DataTemplate x:DataType="viewModels:IFlightStatusResultItemViewModel">
                                <OtherCustomViewControl />
                            </DataTemplate>
                        </controls:ExtendedStackLayout.ItemTemplate>
                    </controls:ExtendedStackLayout>
                </ScrollView>
            </pullToRefresh:PullToRefreshLayout>

        </Grid>`

**Comment by jamesmontemagno** [comment]
Please use the RefreshView as this is officially deprecated now https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview
